# For the basic functionality, emails are the only 
# fields you need to fill.
emails:
  # Email that will be used to send emails. Tested with gmail.
  source_email:
    address: login
    password: pass

  # List of email addresses that should receive info.
  target_emails:
    - sample@gmail.com

# Enabling specific events and changing messages.
# You can use 2 special variables: $IP and $USER, self explanatory.
notifications:
  auth_fail:
    enable: true
    message: Failed login attempt from $IP for user $USER.
  auth_success: 
    enable: true
    message: Successful login from $IP for user $USER.


# List of IPs that would not trigger any events.
whitelist: []

# Internal config, you probably shouldn't change anything here.
configuration:
  # How frequent to check for events in `ssh.service` (in seconds).
  polling_freq: 0.1

  # Path to log file. If empty, `./notifier.log` will be used.
  log_file: #./notifier.log

  # Should script write to COUT?
  enable_cout_log: true
  
  # Should script write to `log_file`?
  enable_file_log: true
