# For the basic functionality, emails are the only 
# fields you need to fill.
emails:
  # Email that will be used to send emails. Tested with gmail.
  # https://support.google.com/accounts/answer/185833
  source_email:
    address: sample@gmail.com
    password: pass

  # List of email addresses that should receive info.
  target_emails:
    - target@gmail.com

# Enabling specific events and changing messages.
# You can use 3 special variables: $IP, $USER and $MACHINE, self explanatory.
notifications:
  auth_fail:
    enable:  true
    subject: Failed login attempt on machine $MACHINE.
    message: Failed login attempt from $IP for user $USER.
  auth_success: 
    enable:  true
    subject: Successful login attempt on machine $MACHINE.
    message: Successful login from $IP for user $USER.


# List of IPs that would not trigger any events.
whitelist: []
  # - 127.0.0.1

# Internal config, you probably shouldn't change anything here.
configuration:
  # How frequent to check for events in `ssh.service` (in seconds).
  polling_freq: 0.1

  # Path to log file. If empty, `./notifier.log` will be used.
  log_file: ./notifier.log